kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane  # The master node
- role: worker         # Worker node 1
- role: worker         # Worker node 2
- role: worker         # Worker node 3